### ISSUE TITLE
Email encoding issue

### ISSUE THREAD

**Issue by NerdyNinja11** [jsyiek/AU2#82]
Emails still have encoding issues: One I just received contained "Ã©" instead of "é"
It is correct on the website, so it must be correct in the database.

**Comment by jsyiek** [comment]
I'd start by looking at Paramiko's encoding format when writing the `.email` file.

**Comment by thenewtonium** [comment]
> I'd start by looking at Paramiko's encoding format when writing the `.email` file.

That shouldn't be an issue right? Since it just `put`s the file from disk, which is already encoded in utf-8.

I reckon the issue is that our email headers don't specify the encoding, and so email clients are assuming it's ISO-8859-2 or sth... in which case adding a header `Content-Type: text/plain; charset=UTF-8` (or `Content-Type: text/html; charset=UTF-8` if we prefer) should do the trick?
